package com.mjrenew.mjrenew_backend.enums;

public enum EstadoAntiguedad {
    PIEZA_CAPTURADA,
    EN_EVALUACION,
    CALCULANDO_PRESUPUESTO,
    PRESUPUESTO_PRESENTADO,
    PAGO_EN_ESCROW,
    HORARIO_RECOLECCION_AGENDADO,
    EN_RECOLECCION,
    RECIBIDO_EN_TALLER,
    EN_RESTAURACION,
    AVANCE_PUBLICADO,
    RESTAURACION_LISTA,
    DECISION_EN_TALLER,
    HORARIO_ENTREGA_AGENDADO,
    EN_DEVOLUCION_PROPIETARIO,
    ENTREGADO_AL_PROPIETARIO,
    EN_CATALOGO,
    LINK_PAGO_ENVIADO,
    SOLICITUD_DEVOLUCION_TALLER,
    CANCELADA_NO_CUMPLE,
    CANCELADA_DUENO_DECLINO,
    CANCELADA_RECOLECCION,
    CANCELADA_ENTREGA,
    RESTAURACION_COMPLETADA,
    VENTA_COMPLETADA,
    DEVUELTA_DESDE_TALLER
}