spring.application.name=mjrenew-backend

spring.thymeleaf.cache=false

# ============================================================
# PostgreSQL
# ============================================================

spring.config.import=optional:classpath:application-local.properties

# ============================================================
# JPA / Hibernate
# ============================================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true